import type { Metadata } from "next";
import "./globals.css";
import { Protest_Revolution, Archivo_Black } from 'next/font/google'
import HackerBackground from "@/components/ui/hackerbg";

const protestRevolution = Protest_Revolution({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-protest-revolution',
})

const archivoBlack = Archivo_Black({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-archivo-black',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${protestRevolution.variable} ${archivoBlack.variable}`}>
      <body className="relative bg-black">
        <HackerBackground color="#8364FF" fontSize={8} speed={1} className="opacity-1 bg-transparent" />
        {children}
      </body>
    </html>
  );
}
